name: testssfds

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "**"
jobs:

  tests:

    runs-on: self-hosted
    defaults:
      run:
        shell: zsh

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Compile
      run: xcodebuild -scheme SwiftCV -destination 'generic/platform=iOS Simulator'
