name: testssfds

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "**"
jobs:
  tests:

    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set Default Scheme
      run: echo hiii
