name: Simulator Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "**"
jobs:
  build-and-test:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: xcodebuild -scheme SwiftCV -destination 'generic/platform=iOS Simulator'

