name: Simulator Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "**"
      - "!experiment/**"

defaults:
  run:
    shell: zsh --login --errexit --pipefail {0}

jobs:
  build-and-test:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: echo pwd
    - name: Run tests
      run: >
        xcodebuild -scheme MyApp -sdk iphonesimulator -destination name=iphone-${{ runner.name }}
        test | xcbeautify
