name: testssfds

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "**"
jobs:

  tests:

    runs-on: self-hosted
    defaults:
      run:
        shell: zsh {0}
        working-directory: ./SwiftCV/SwiftCV

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Compile
      run: pwd
