name: testssfds

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "**"
jobs:
  defaults:
    run:
      shell: zsh

  tests:

    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Compile
      run: xcodebuild -scheme SwiftCV -destination 'generic/platform=iOS Simulator'
