name: Simulator Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "**"
jobs:
  build-and-test:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set Default Scheme
      run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default

