name: Commits

on:
  pull_request:
    branches: ["master"]
    types: [opened, reopened, edited]
  push:
    branches: ["master"]

jobs:
  use_share:
    uses: ./.github/workflows/shared.yml
    with:
      branch: master
      title: ${{ github.event.pull_request.title }}
      repo: jm-jimenez/CommitsRunner.git
      type: ${{ github.event_name }}
